/* Generated By:JavaCC: Do not edit this line. CodeAnalyzerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CodeAnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int END = 5;
  /** RegularExpression Id. */
  int PARENT_ABRE = 6;
  /** RegularExpression Id. */
  int PARENT_FECHA = 7;
  /** RegularExpression Id. */
  int SOMA = 8;
  /** RegularExpression Id. */
  int SUBUTRACAO = 9;
  /** RegularExpression Id. */
  int DIVISAO = 10;
  /** RegularExpression Id. */
  int MULTIPLICACAO = 11;
  /** RegularExpression Id. */
  int MODULO = 12;
  /** RegularExpression Id. */
  int OPERANDO = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int FUNC = 15;
  /** RegularExpression Id. */
  int VAR = 16;
  /** RegularExpression Id. */
  int TEXT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"EOF\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"%\"",
    "<OPERANDO>",
    "<NUM>",
    "<FUNC>",
    "<VAR>",
    "<TEXT>",
  };

}
