/* Generated By:JavaCC: Do not edit this line. CodeAnalyzerConstants.java */
package com.fcteste.core;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CodeAnalyzerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int END = 5;
  /** RegularExpression Id. */
  int PARENT_OPEN = 6;
  /** RegularExpression Id. */
  int PARENT_CLOSE = 7;
  /** RegularExpression Id. */
  int SUM = 8;
  /** RegularExpression Id. */
  int SUBTRAC = 9;
  /** RegularExpression Id. */
  int DIVISION = 10;
  /** RegularExpression Id. */
  int MULTIPLICATION = 11;
  /** RegularExpression Id. */
  int MODULE = 12;
  /** RegularExpression Id. */
  int XOR = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int ASSIGNMENT = 17;
  /** RegularExpression Id. */
  int EQUAL = 18;
  /** RegularExpression Id. */
  int DIFFERENT = 19;
  /** RegularExpression Id. */
  int GREATER = 20;
  /** RegularExpression Id. */
  int LESS = 21;
  /** RegularExpression Id. */
  int GREQUAL = 22;
  /** RegularExpression Id. */
  int LSEQUAL = 23;
  /** RegularExpression Id. */
  int CAND = 24;
  /** RegularExpression Id. */
  int COR = 25;
  /** RegularExpression Id. */
  int CXOR = 26;
  /** RegularExpression Id. */
  int CNOT = 27;
  /** RegularExpression Id. */
  int POINT = 28;
  /** RegularExpression Id. */
  int PCOMMA = 29;
  /** RegularExpression Id. */
  int NUMBER = 30;
  /** RegularExpression Id. */
  int TEXTVALID = 31;
  /** RegularExpression Id. */
  int OTHER = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"EOF\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"%\"",
    "\"^\"",
    "\"&\"",
    "\"|\"",
    "\"~\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"^^\"",
    "\"!\"",
    "\".\"",
    "\";\"",
    "<NUMBER>",
    "<TEXTVALID>",
    "<OTHER>",
  };

}
