/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fcteste.view;

import com.fcteste.controller.ControllView;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;

/**
 *
 * @author Julio M. C. Dias
 */
public class ViewMain extends javax.swing.JFrame {

    private final ControllView cView;
    private final DefaultListModel dlm;

    /**
     * Creates new form ViewPrincipal
     *
     * @param cView
     */
    public ViewMain(ControllView cView) {
        this.cView = cView;
        dlm = new DefaultListModel();
        initComponents();
        jListArq.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFlocalProjeto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArq = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTFLinTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jbtnProcurar = new javax.swing.JButton();
        jbtnGerarArquivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTFLinComando = new javax.swing.JTextField();
        jbtnNovoProjeto = new javax.swing.JButton();
        jbtnAnalizarProjeto = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jbtnSeleAll = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTFOperandos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTfQtMetodos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFOperadoresUni = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFOperadoresTotais = new javax.swing.JTextField();
        jTFArquivos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Projeto Java:");

        jListArq.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListArqValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListArq);

        jLabel2.setText("Numero de Linhas:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTFLinTotal.setEditable(false);
        jTFLinTotal.setText("0");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel3.setText("Arquivos:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("FCTeste");

        jbtnProcurar.setText("Procurar...");
        jbtnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProcurarActionPerformed(evt);
            }
        });

        jbtnGerarArquivo.setText("Gerar Arquivo CSV");
        jbtnGerarArquivo.setEnabled(false);
        jbtnGerarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGerarArquivoActionPerformed(evt);
            }
        });

        jLabel5.setText("Chamada de metodos:");

        jTFLinComando.setEditable(false);
        jTFLinComando.setText("0");

        jbtnNovoProjeto.setText("Novo Projeto");
        jbtnNovoProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoProjetoActionPerformed(evt);
            }
        });

        jbtnAnalizarProjeto.setText("Analisar Projeto");
        jbtnAnalizarProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnalizarProjetoActionPerformed(evt);
            }
        });

        jbtnSeleAll.setText("Selecionar Tudo");
        jbtnSeleAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleAllActionPerformed(evt);
            }
        });

        jLabel6.setText("Operandos:");

        jTFOperandos.setEditable(false);
        jTFOperandos.setText("0");

        jLabel7.setText("Definição de metodos:");

        jTfQtMetodos.setEditable(false);
        jTfQtMetodos.setText("0");

        jLabel10.setText("Operador. Unitários:");

        jTFOperadoresUni.setEditable(false);
        jTFOperadoresUni.setText("0");

        jLabel11.setText("Operador. Totais:");

        jTFOperadoresTotais.setEditable(false);
        jTFOperadoresTotais.setText("0");

        jTFArquivos.setEditable(false);
        jTFArquivos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(360, 360, 360))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFlocalProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnProcurar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jbtnSeleAll)))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel2)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFOperadoresUni, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTFLinTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(jTfQtMetodos)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTFOperadoresTotais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTFOperandos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTFLinComando, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbtnGerarArquivo)
                                        .addGap(136, 136, 136)))))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jbtnAnalizarProjeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnNovoProjeto)
                        .addGap(164, 164, 164))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFlocalProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnProcurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAnalizarProjeto)
                    .addComponent(jbtnNovoProjeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnSeleAll))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTFLinTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTFLinComando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTfQtMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTFOperandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTFOperadoresUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTFOperadoresTotais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addComponent(jbtnGerarArquivo)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGerarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGerarArquivoActionPerformed
        cView.creatCSV();
    }//GEN-LAST:event_jbtnGerarArquivoActionPerformed

    private void jbtnAnalizarProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnalizarProjetoActionPerformed
        cView.analyzeProject(jTFlocalProjeto.getText());
        jbtnAnalizarProjeto.setEnabled(false);
        jbtnGerarArquivo.setEnabled(true);
    }//GEN-LAST:event_jbtnAnalizarProjetoActionPerformed

    private void jbtnNovoProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoProjetoActionPerformed
        cView.cleanProject();
        jTFlocalProjeto.setText("");
        jbtnAnalizarProjeto.setEnabled(true);
        jbtnGerarArquivo.setEnabled(false);
    }//GEN-LAST:event_jbtnNovoProjetoActionPerformed

    private void jbtnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProcurarActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Abrir diretorio java do projeto");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);  // disable the "All files" option.
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTFlocalProjeto.setText(chooser.getSelectedFile().toString());
            cView.cleanProject();
            jbtnAnalizarProjeto.setEnabled(true);
            jbtnGerarArquivo.setEnabled(false);
        }

    }//GEN-LAST:event_jbtnProcurarActionPerformed

    private void jbtnSeleAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleAllActionPerformed
        int sizeList[] = new int[dlm.size()];
        for (int i = 0; i < dlm.size(); i++) {
            sizeList[i] = i;
        }

        jListArq.setSelectedIndices(sizeList);
        cView.selectionFiles();
    }//GEN-LAST:event_jbtnSeleAllActionPerformed

    private void jListArqValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListArqValueChanged
        cView.selectionFiles();
    }//GEN-LAST:event_jListArqValueChanged

    //   gets
    public DefaultListModel getDlm() {
        return dlm;
    }

    public JList<String> getjListArq() {
        return jListArq;
    }

    public void setjTFQtMetodos(int value) {
        jTfQtMetodos.setText((value < 0) ? "--" : String.valueOf(value));
    }

    public void setjTFLinComando(int value) {
        jTFLinComando.setText((value < 0) ? "--" : String.valueOf(value));
    }

    public void setjTFLinTotal(int value) {
        jTFLinTotal.setText((value < 0) ? "--" : String.valueOf(value));
    }

    public void setjTFOperadoresTotais(int value) {
        jTFOperadoresTotais.setText((value < 0) ? "--" : String.valueOf(value));
    }

    public void setjTFOperadoresUni(int value) {
        jTFOperadoresUni.setText((value < 0) ? "--" : String.valueOf(value));
    }

    public void setjTFOperandos(int value) {
        jTFOperandos.setText((value < 0) ? "--" : String.valueOf(value));
    }

    public void setjTFArquivos(int value) {
        jTFArquivos.setText((value < 0) ? "--" : String.valueOf(value));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListArq;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTFArquivos;
    private javax.swing.JTextField jTFLinComando;
    private javax.swing.JTextField jTFLinTotal;
    private javax.swing.JTextField jTFOperadoresTotais;
    private javax.swing.JTextField jTFOperadoresUni;
    private javax.swing.JTextField jTFOperandos;
    private javax.swing.JTextField jTFlocalProjeto;
    private javax.swing.JTextField jTfQtMetodos;
    private javax.swing.JButton jbtnAnalizarProjeto;
    private javax.swing.JButton jbtnGerarArquivo;
    private javax.swing.JButton jbtnNovoProjeto;
    private javax.swing.JButton jbtnProcurar;
    private javax.swing.JButton jbtnSeleAll;
    // End of variables declaration//GEN-END:variables
}
